version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mysql:
    image: mysql
    volumes:
      - mysql_data_1:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: order-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - mysql



volumes:
  data:
  mysql_data_1:

networks:
  default:
    name: mongodb_network