server:
  port: 8083

spring:
  config:
    import: secret.yml
  application:
    name: image-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  file:
    name: ./log/image-service.log