server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/inventory-service
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: inventory-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  file:
    name: ./log/inventory-service.log